name: flutter_duration_picker
description: A widget for picking durations, inspired by Material Time Picker.
version: 1.0.4
author: Chris Harris <c@harrischris.com>
homepage: https://github.com/cdharris/flutter_duration_picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
  sdk: ">=2.16.1 <3.0.0"
